export const HISTORICAL = 'HISTORICAL';
export const RESET_HISTORICAL = 'RESET_HISTORICAL';
export const RECEIVE_HISTORICAL = 'RECEIVE_HISTORICAL';
export const HISTORICAL_ERROR = 'HISTORICAL_ERROR';
